#!/bin/bash

WQ_VERSION="1.0"
WQ_COMMAND=wq
WQ_FILE=/usr/local/bin/$WQ_COMMAND
PROJECT_NAME=$1
ROOT_DIRECTORY=/var/www/html
DOWNLOAD_PATH=$ROOT_DIRECTORY/$PROJECT_NAME
LANGUAGE=en_US
DB_USER=root
DB_PASS=root
BASE_URL=http://localhost

if ! command -v wp > /dev/null 2>&1; then
    echo "Please install WP CLI. The command line interface for WordPress."
    echo "Visit https://wp-cli.org/"
    exit
fi

if ! command -v $WQ_COMMAND > /dev/null 2>&1; then
    sudo cp $WQ_COMMAND $WQ_FILE
    sudo chmod +x $WQ_FILE
    if command -v $WQ_COMMAND > /dev/null 2>&1; then
    	#rm $WQ_COMMAND
    	echo "WPCLI Quick installed successfully."
    	echo "Use command as follow:"
        echo "$WQ_COMMAND <project_name> <database_user> <database_password> <base_url>"
        echo "Example: $WQ_COMMAND myproject root root http://localhost"
    else
    	echo "Something went wrong, please report issue at following url"
    	echo "https://github.com/enishant/wpcli-quick-start/issues/new"
	fi
    exit
fi

if [ -z "$PROJECT_NAME" ]; then
  echo "Project name is empty"
  echo "$WQ_COMMAND <project_name> <database_user> <database_password> <base_url>"
  echo "Example: $WQ_COMMAND myproject root root http://localhost"
  exit
fi

if [ ! -d "$DOWNLOAD_PATH" ]; then
  mkdir $DOWNLOAD_PATH
  cd $DOWNLOAD_PATH
else
  echo "Path $DOWNLOAD_PATH is already in use for project $PROJECT_NAME"
  echo "Please use another project name."
  exit
fi

if [ ! -z "$2" ]; then
  DB_USER=$2
fi

if [ ! -z "$3" ]; then
  DB_PASS=$3
fi

if [ ! -z "$4" ]; then
  BASE_URL=$4
fi

wp core download --path=$DOWNLOAD_PATH --locale=$LANGUAGE

wp config create --dbname=$PROJECT_NAME --dbuser=$DB_USER --dbpass=$DB_PASS --locale=$LANGUAGE

wp db create --dbuser=$DB_USER --dbpass=$DB_PASS

wp core install --url=$BASE_URL/$PROJECT_NAME --title=$PROJECT_NAME --admin_user=$PROJECT_NAME --admin_password=$PROJECT_NAME --admin_email=admin@example.com

wp plugin delete hello akismet

wp rewrite structure '/%postname%/'

wp rewrite flush
